### ISSUE TITLE
Feature request: Make the CloudFront Distribution available as a property

### ISSUE THREAD

**Issue by matthewskahn** [awslabs/cloudfront-hosting-toolkit#18]
### Use case

I would like to use the CloudFront Distribution domain to configure a Congito User Pool Client.

### Solution/User Experience

I would like to be able to do:

```javascript
const { distribution } = new Hosting(this, 'Hosting', {...});
```

### Alternative solutions

```markdown
Currently, I have used `tryFindChild` on the construct node itself to drill down to what I need.
```

**Comment by cornelcroi** [comment]
The CloudFront Distribution is now exposed as a public readonly property on the Hosting construct.


You can now access the CloudFront Distribution like this:
```typescript
const { distribution } = new Hosting(this, 'Hosting', {...});
