### ISSUE TITLE
Bug: Domain name validation doesn't accept TLDs longer than 6 characters

### ISSUE THREAD

**Issue by zoeyim** [awslabs/cloudfront-hosting-toolkit#19]
### Expected Behaviour

Domain name input should accept any valid domain name. 

### Current Behaviour

Domains with TLDs longer than 6 characters, such as `.services`, are rejected. 

### Code snippet

```python
✔ Do you own a domain name that you would like to use? › Yes


? Please provide your domain name in the following formats: www.mydomainname.com or mydomainname.com ? › test.services
› Domain name format must be www.mydomainname.com or mydomainname.com
```

### Possible Solution

https://github.com/awslabs/cloudfront-hosting-toolkit/blob/main/bin/cli/shared/constants.ts#L54

Change the current regex:
```
  /^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}$/i;
```

to:
```
  /^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,}$/i;
```

### Steps to Reproduce

1. Run `cloudfront-hosting-toolkit init`
2. Follow the steps until you get to the prompt `Please provide your domain name in the following formats: www.mydomainname.com or mydomainname.com`
3. Enter any domain name with a TLD longer than 6 characters, e.g. `test.services`

**Comment by cornelcroi** [comment]
Thank you for your contribution! The changes have been merged.

Changes made:
- Updated the domain name validation regex to accept TLDs longer than 6 characters
- Changed TLD pattern from `{2,6}` to `{2,}` to support longer TLDs like .services
- Maintains existing validation rules for the rest of the domain name

This fixes #19. You can now use domain names with longer TLDs like example.services.
