### ISSUE TITLE
Feature request: Allow creation of multiple pipelines per repository

### ISSUE THREAD

**Issue by sazuma-0612** [awslabs/cloudfront-hosting-toolkit#22]
### Use case

When using AWS CDK to create CI/CD pipelines for multiple branches in a repository, we need to create separate pipelines for each branch within the same AWS account. 

However, the current implementation generates pipeline names in the format [repoOwner]-[repoName], which leads to the error "[pipeline name] already exists" when trying to create additional pipelines for the same repository. 

This limits us to creating only one pipeline per repository in a single AWS account.

### Solution/User Experience

Enhance the pipeline creation functionality in AWS CDK to support multiple pipelines per repository within the same AWS account. 

This would allow users to set up separate pipelines for different branches or environments without the need for multiple AWS accounts.

**Comment by cornelcroi** [comment]
This feature has been implemented and merged.

Changes made:
- Modified pipeline name format to include branch name: `[repoOwner]-[repoName]-[branchName]`
- Pipeline names are now unique per branch within the same repository
- Maintained existing functionality for S3-triggered pipelines
- Kept name sanitization to handle special characters

You can now create multiple pipelines for different branches in the same repository. For example:
- `owner-repo-main`
- `owner-repo-develop`
- `owner-repo-feature-x`

This enables you to set up separate pipelines for different branches/environments without needing multiple AWS accounts. Closes #20.
