### ISSUE TITLE
Bug: Long names are not truncated to less than 64 causing resource creation to fail

### ISSUE THREAD

**Issue by michaellisitsa** [awslabs/cloudfront-hosting-toolkit#37]
### Expected Behaviour

Repositories with a combination of repo name, branch, region etc. that combine to greater than 64 characters should be truncated to match limits.

After I changed the repo name to be shorter it worked. The only other probably unrelated change was using `aws-vault exec xxx --no-session` instead

### Current Behaviour

For a repo `cloudfront-hosting-toolkit-nextjs` with repo `master` and region `ap-southeast-2` there is an error because some resources cause a total string of 68 characters (hosting-main-cloudfront-hosting-toolkit-nextjs-master-ap-southeast-2)

### Code snippet

```python
**Cloudformation Stack event:**

2024-10-29 15:34:54 UTC+1100 | HostingUriStorexxx | CREATE_FAILED | - | Resource handler returned message: "Invalid request provided: 2 validation errors detected: Value 'hosting-main-cloudfront-hosting-toolkit-nextjs-master-ap-southeast-2' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64; Value 'hosting-main-cloudfront-hosting-toolkit-nextjs-master-ap-southeast-2' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9-_]{1,64} (Service: CloudFront, Status Code: 400, Request ID: xxx" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
-- | -- | -- | -- | --
2024-10-29 15:34:54 UTC+1100 | HostingHostingInfrastructurexxx | CREATE_FAILED | - | Resource handler returned message: "Invalid request provided: AWS::CloudFront::OriginAccessControl" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
024-10-29 15:34:54 UTC+1100 | HostingHostingInfrastructureResponseHeadersPolicy630F57EC | CREATE_IN_PROGRESS

**Logs**
hosting-main-cloudfront-hosting-toolkit-nextjs-master |  2/52 | 3:34:54 pm | CREATE_FAILED        | AWS::CloudFront::OriginAccessControl   | Hosting/HostingInfrastructure/OAC (HostingHostingInfrastructureOACF290641F) Resource handler returned message: "Invalid request provided: AWS::CloudFront::OriginAccessControl" (RequestToken: 46b67420-8200-6af3-3508-2c50a800e467, HandlerErrorCode: InvalidRequest)
-- | -- | -- | -- | -- | --
hosting-main-cloudfront-hosting-toolkit-nextjs-master |  2/52 | 3:34:54 pm | CREATE_FAILED        | AWS::CloudFront::KeyValueStore         | Hosting/UriStore (HostingUriStoreC5D8CAEE) Resource handler returned message: "Invalid request provided: 2 validation errors detected: Value 'hosting-main-cloudfront-hosting-toolkit-nextjs-master-ap-southeast-2' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64; Value 'hosting-main-cloudfront-hosting-toolkit-nextjs-master-ap-southeast-2' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9-_]{1,64} (Service: CloudFront, Status Code: 400, Request ID: a6c1e5e5-1222-46a3-9f24-5adb7d396396)" (RequestToken: fcc52903-ef6d-d1bf-6e3f-c43c70cd2aea, HandlerErrorCode: InvalidRequest)
```

### Possible Solution

The KeyValueStore creation command seems to use `truncateString` in below https://github.com/awslabs/cloudfront-hosting-toolkit/blob/2cfde47c7c379094681249481e01f81787182961/lib/hosting.ts#L88-L91 but not sure if I'm looking at the right place as haven't worked with cloud formation or cdk before

### Steps to Reproduce

1. Create a repo with a title that has the same length as `cloudfront-hosting-toolkit-nextjs` with the repo of the same length as `master`.
2. Run `init` command, which will fail
3. Observe it tries to create a resource with name `hosting-main-cloudfront-toolkit-nextjs-ap-southeast-2`, which is of length 68.
4. Observe log file generated which advises it does not meet maximum of 64.

**Comment by cornelcroi** [comment]
Thank you for reporting this issue regarding the KeyValueStore name length limitation. 
This has been fixed in version `1.1.21` of the cloudfront-hosting-toolkit.
