### ISSUE TITLE
Bug: Route53 A record not usiong the correct target domain

### ISSUE THREAD

**Issue by niklas-palm** [awslabs/cloudfront-hosting-toolkit#4]
### Expected Behaviour

A Route53 A record with alias target, targeting the Cloudfront domain.

### Current Behaviour

A Route53 A record with alias target, targeting a substring of Cloudfront domain.

### Code snippet

```python
N/A
```

### Possible Solution

When the alias record is created, the a record target should be the cloudfront domain name. However, there's a bug where the first 8 characters of the domain name are omitted:
```javascript
const cFCNAMEExists = await checkCFCNAMEExists(
  hostingConfiguration.domainName,
  domainName.substring(8),
  hostingConfiguration.hostedZoneId
);
```
[This](https://github.com/awslabs/cloudfront-hosting-toolkit/blob/7a1bc3ce623d0a03a09844b977301ecb4ea25b00/bin/cli/actions/deploy.ts#L203) is the location in the code. Will submit PR.

### Steps to Reproduce

N/A

**Comment by cornelcroi** [comment]
PR merged with the fix.
