### ISSUE TITLE
What happened to the Roadmap page?

### ISSUE THREAD

**Issue by GerardKetuma** [awslabs/cloudfront-hosting-toolkit#40]
What happened to the roadmap page that was here: [Public Roadmap](https://github.com/awslabs/cloudfront-hosting-toolkit/blob/main/docs/roadmap.md)

I want to use this with my new project but really scared that this is going to get abandoned.

**Comment by cornelcroi** [comment]
Hi,

Here is the roadmap https://github.com/awslabs/cloudfront-hosting-toolkit/blob/main/roadmap.md
