### ISSUE TITLE
You didn't fix #3

### ISSUE THREAD

**Issue by sholtomaud** [awslabs/cloudfront-hosting-toolkit#6]
### Expected Behaviour

fixed

### Current Behaviour

not fixed

### Code snippet

```python
fix it
```

### Possible Solution

fix it

### Steps to Reproduce

fix #3 

try npm i

**Comment by cornelcroi** [comment]
Can you please be more specific ? Have you installed the latest version 1.1.9 ?
Can you give an example of what exactly is wrong? Or the stack trace with the error?
It would help me to better understand the problem.
Thanks.

**Comment by sholtomaud** [comment]
![image](https://github.com/awslabs/cloudfront-hosting-toolkit/assets/398402/137ae9ac-b16f-426d-a2b0-e82714690748)

**Comment by sholtomaud** [comment]
![image](https://github.com/awslabs/cloudfront-hosting-toolkit/assets/398402/2a462735-1153-47bb-9d42-bde89548611d)

**Comment by sholtomaud** [comment]
Also this is **always** galling and a bad look for billionaires

`55 packages are looking for funding
  run `npm fund` for details`

**Comment by sholtomaud** [comment]
Support those that support you

**Comment by cornelcroi** [comment]
Can you have another look at the readme page ? 
The "Getting Started with CDK" section has been updated and the sample code provided should work fine.
Here is the sample code provided:


```
  import { RepositoryConnection, Hosting } from '@aws/cloudfront-hosting-toolkit';

  ...

  const config = {
      repoUrl: "https://github.com/USERNAME/REPOSITORY.git",
      branchName: "main",
      framework: "frameworkname"
  };
  const repositoryConnection = new RepositoryConnection(this, "MyRepositoryConnection", config)

  new Hosting(this, "MyHosting", {
      hostingConfiguration: config,
      buildFilePath: "buildConfigurationFile.yml",
      connectionArn: repositoryConnection.connectionArn,
      cffSourceFilePath: "index.js"
  });
  
```

**Comment by sholtomaud** [comment]
fixed
